import Navbar from "@/components/sections/navbar";
import type { Metadata } from "next";
import { TooltipProvider } from '@/components/ui/tooltip'
import Header from "@/components/sections/header";
import { auth } from "../../../auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth()

  if (!session.user) return null

  return (
    <html lang="en">
      <body>
          <TooltipProvider>
            <Navbar />
            <Header profile_img={session.user.image} user={session.user} />
            {children}
          </TooltipProvider>
      </body>
    </html>
  );
}
